import "bootstrap/dist/css/bootstrap.css";
import "../styles/index.scss";

export const metadata = {
  title: "Mosibello",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en-US">
      <body>{children}</body>
    </html>
  );
}
