import "bootstrap/dist/css/bootstrap.css";
import "../styles/index.scss";
import Layout from "@/components/Layout";

export const metadata = {
  title: "Mosibello",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en-US">
      <body>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
